In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
# 定义dropout层
def dropout_layer(X, dropout):  # dropout指的是丢弃率
    assert 0 <= dropout <= 1
    if dropout == 1:
        return torch.zeros_like(X)  # 全部丢弃
    if dropout == 0:
        return X    # 不丢弃
    # 这里mask是一个只有0-1的向量
    # 先随机生成一个0-1均匀分布的向量，必然有dropout概率的值小于dropout，将它们设置为0
    mask = (torch.rand(X.shape) > dropout).float()
    return mask * X / (1.0 - dropout)

In [3]:
# 测试函数功能是否正常
X= torch.arange(16, dtype = torch.float32).reshape((2, 8))
print(X)
print(dropout_layer(X, 0.))
print(dropout_layer(X, 0.5))
print(dropout_layer(X, 1.))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14.],
        [ 0., 18.,  0., 22.,  0., 26., 28.,  0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
