pytorch 并不能存储模型的结构，只能存储模型的参数

1. 加载和保存张量

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file') # 将张量存储起来

In [2]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [3]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')   # 可以存储张量列表
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [4]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')    # 可以存储张量字典
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

2. 加载和保存模型张量

In [5]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

net = MLP()
X = torch.rand(2, 20)
Y = net(X)

In [6]:
torch.save(net.state_dict(), 'mlp.params')

In [7]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [8]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])